### ISSUE TITLE
Symfony?

### ISSUE THREAD

**Issue by ivanportillo** [omarsotillo/MoviesAndChill-backend#1]
Really? 

![](http://i.imgur.com/60bts.gif)

**Comment by sgomez** [comment]
@ivanportillo and other frontend developer usual conversation:

![image](https://user-images.githubusercontent.com/580701/37568572-35823f9a-2ad7-11e8-8ae6-0fdb8f66508f.png)

**Comment by omarsotillo** [comment]
@ivanportillo @sgomez se migra a typescript o que?
